#!/bin/bash

g++ -Wall -pedantic -o "$2" "$1" && ./"$2"
inotifywait -q -m -e close_write "$1" "$3" |
while read -r filename event; do
	clear;
	printf "\nUpdate at %s\n" $( date +"%T" );
	g++ -Wall -pedantic -o "$2" "$1" && ./"$2"
done
