#!/bin/bash

clear;
g++ -Wall -pedantic -g src/*.cpp -o main && ./main;

inotifywait -q -m -e close_write src/*.cpp data/* |
while read -r filename event; do
	clear;
	printf "\nUpdate at %s\n" $( date +"%T" );
	g++ -Wall -pedantic -g src/*.cpp -o main && ./main;
done
