#!/bin/bash

g++ -Wall -pedantic -g -o "$2" "$1" && valgrind --leak-check=full ./"$2";

inotifywait -q -m -e close_write "$1" |
while read -r filename event; do
	clear;
	printf "\nUpdate at %s\n" $( date +"%T" );
	g++ -Wall -pedantic -g -o "$2" "$1" && valgrind --leak-check=full ./"$2";
done
