#!/bin/bash

inotifywait -q -m -e close_write src/*.*pp src/*/*.*pp examples/* ./examples/sources.cfg |
while read -r filename event; do
	clear;
	printf "\nUpdate at %s\n" $( date +"%T" );
	make compile run
done